### ISSUE TITLE
Reusing ARM Toolchain

### ISSUE THREAD

**Issue by crispyross** [felixjones/gba-toolchain#25]
Currently, the ARM toolchain is always searched for at the path `${CMAKE_CURRENT_LIST_DIR}/arm-gnu-toolchain`. Since the toolchain is ~700 MB, it would be nice if there was a way to reuse it across projects, perhaps by searching in $PATH or passing in the path in ARM_GNU_TOOLS.

**Comment by felixjones** [comment]
The entire `gba-toolchain` is re-usable across projects (just set `-DCMAKE_TOOLCHAIN_FILE=` to wherever it is on your disk), you shouldn't need to download it over and over again, at least for multiple GBA toolchain projects.

I like the idea of using a pre-installed ARM toolchain, for the cases where people already have one on their machine. Perhaps an environment variable and/or a CMake variable. Searching path sounds cool, but my fear would be finding toolchains that look like ARM's, but actually aren't.

**Comment by felixjones** [comment]
Resolved with 3.0 rewrite
