### ISSUE TITLE
Build fails with mutiple gbafix arguments

### ISSUE THREAD

**Issue by Daft-Freak** [felixjones/gba-toolchain#38]
```cmake
gba_target_objcopy(first FIX_HEADER TITLE "GAME TITLE" GAME_CODE "AAAA")
```
... or any more than one of `TITLE/GAME_CODE/MAKER_CODE/VERSION` results in an error like:

```
Fixing header first.gba -tGAME TITLE
/bin/sh: 1: -cAAAA: not found
```

I'm guessing a ; got somewhere it shouldn't...

**Comment by felixjones** [comment]
I'll look into this
Does removing the quotes around your `GAME_CODE` argument fix it?

**Comment by Daft-Freak** [comment]
Nope. Using a title without spaces and no quotes doesn't help either.

**Comment by felixjones** [comment]
In `cmake/Gba.cmake` line `326` there's:
```cmake
            COMMAND "${GBAFIX}" "${objcopyOutput}" ${gbafixArgs}
```
Could you try swapping those two arguments around to:
```cmake
            COMMAND "${GBAFIX}" ${gbafixArgs} "${objcopyOutput}"
```

**Comment by Daft-Freak** [comment]
Hmm, no affect... but looking at the verbose output it's not getting that far:
```
Copying object first.gba
/usr/bin/arm-none-eabi-objcopy -O binary /home/daftfreak/workspace/gba/gba-toolchain/samples/01\ My\ first\ GBA\ demo/build/first.elf first.gba
/usr/bin/cmake -E echo Fixing\ header\ first.gba\ -tGAME\ TITLE;-cAAAA
Fixing header first.gba -tGAME TITLE
/bin/sh: 1: -cAAAA: not found
```

Hmm, changing the line above to move `${gbafixArgs}` out of the quotes works:
`COMMAND "${CMAKE_COMMAND}" -E echo "Fixing header ${objcopyOutput}" ${gbafixArgs}`

```
Copying object first.gba
/usr/bin/arm-none-eabi-objcopy -O binary /home/daftfreak/workspace/gba/gba-toolchain/samples/01\ My\ first\ GBA\ demo/build/first.elf first.gba
/usr/bin/cmake -E echo Fixing\ header\ first.gba -tGAME\ TITLE -cAAAA
Fixing header first.gba -tGAME TITLE -cAAAA
/opt/devkitpro/tools/bin/gbafix first.gba -tGAME\ TITLE -cAAAA
ROM fixed!
```

(On an semi-unrelated note that objcopy isn't from the toolchain I'm trying to use...)

**Comment by LunarLambda** [comment]
Don't know how much help this can be, but here's how I execute gbafix in `devkitarm-gba-template`:

https://github.com/LunarLambda/devkitarm-gba-template/blob/main/Makefile#L139-L142

https://github.com/LunarLambda/devkitarm-gba-template/blob/main/Makefile#L179

Though that's GNU Make, not CMake, but it seems like gbafix doesn't care about argument order at least, so it might be a shell argument quoting problem?
