### ISSUE TITLE
libseven example does not build.

### ISSUE THREAD

**Issue by tfinnegan937** [felixjones/gba-toolchain#42]
I have attempted to build the libseven example using the following command:

`cmake -DCMAKE_TOOLCHAIN_FILE=/opt/gba-toolchain/arm-gba-toolchain.cmake ./ && make`

Which produces the following output:

`-- Using ARM GNU toolchain (/home/tim/arm-gnu-toolchain) with GCC 11.3.1
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/gba-toolchain/samples/02 libseven
Scanning dependencies of target seven
[  5%] Building ASM object seven/CMakeFiles/seven.dir/src/hw/dma.s.obj
[ 10%] Building ASM object seven/CMakeFiles/seven.dir/src/hw/input.s.obj
[ 15%] Building ASM object seven/CMakeFiles/seven.dir/src/hw/irq.s.obj
[ 21%] Building ASM object seven/CMakeFiles/seven.dir/src/hw/sram.s.obj
[ 26%] Building ASM object seven/CMakeFiles/seven.dir/src/hw/svc.s.obj
[ 31%] Building ASM object seven/CMakeFiles/seven.dir/src/hw/timer.s.obj
[ 36%] Building C object seven/CMakeFiles/seven.dir/src/util/log.c.obj
[ 42%] Building ASM object seven/CMakeFiles/seven.dir/src/util/mem.s.obj
[ 47%] Building ASM object seven/CMakeFiles/seven.dir/src/util/profile.s.obj
[ 52%] Building ASM object seven/CMakeFiles/seven.dir/src/util/rand.s.obj
[ 57%] Building ASM object seven/CMakeFiles/seven.dir/src/util/simd.s.obj
[ 63%] Building ASM object seven/CMakeFiles/seven.dir/src/util/str.s.obj
[ 68%] Building ASM object seven/CMakeFiles/seven.dir/src/video/bmp.s.obj
[ 73%] Building ASM object seven/CMakeFiles/seven.dir/src/video/oam.s.obj
[ 78%] Linking C static library libseven.a
[ 78%] Built target seven
Scanning dependencies of target gba-minrt
[ 84%] Building ASM object gba-minrt/CMakeFiles/gba-minrt.dir/src/crt0.s.obj
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s: Assembler messages:
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:15: Error: can't open header.s for reading: No such file or directory
make[2]: *** [gba-minrt/CMakeFiles/gba-minrt.dir/build.make:75: gba-minrt/CMakeFiles/gba-minrt.dir/src/crt0.s.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: gba-minrt/CMakeFiles/gba-minrt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

**Comment by tfinnegan937** [comment]
Removing all references to minirt in the libseven CMakeLists file resolves this completely. I believe the update in 3.0.4 that implemented minirt may have broken it

**Comment by LunarLambda** [comment]
the versions of libseven bundled by gba-toolchain are severely outdated anyway. I probably need to work on a PR to get the examples and versions updated. Minrt has gone through extensive updates and changes and so has libseven

**Comment by tfinnegan937** [comment]
Gotcha. I really appreciate the work that you and felixjones have done on this project.

I tried to integrate devkitpro into my CLion setup and it was a nightmare. Despite the bugs, this has been a huge step up from that. 

I will keep reporting issues as I find them, and maybe submit a few PRs of my own.

**Comment by LunarLambda** [comment]
Can you try building https://github.com/LunarLambda/gba-toolchain?

I think I got everything right but I'm not really CMake savvy. Should be a quick PR if it works.

**Comment by tfinnegan937** [comment]
Sure thing. First thing in the morning. I just shut off for the night.

**Comment by LunarLambda** [comment]
So I tested it locally and besides some CMakeLists typos, right now linking fails because gba-toolchain forces `-nostartfiles` as a link flag, whereas minrt is actually compliant with newlib's __libc_init_array/__libc_fini_array scheme and GCC's startfiles.

I've been going back and forth on minrt doing things "the right way", even if it means libc demanding vestigial leftovers of startcode (_init/_fini), and doing it "correct enough" at the cost of needing to maintain and test and research a solution

**Comment by felixjones** [comment]
Perhaps the best short term fix is remove min-rt in gba-toolchain for now until I fix it properly

**Comment by LunarLambda** [comment]
That would be fine. libseven is and will continue to be compatible with devkitARM's CRT, and should be compatible with librom/libmultiboot just as well.

I have written a proper CMakeLists.txt for minrt, so if you want to re-introduce it at a later point, it should work without you needing to add any special code for it

**Comment by LunarLambda** [comment]
Release minrt 0.6.0 which slims down the init and exit code, drops some vestigial nonsense, and is -nostartfiles compatible. My fork now builds cleanly.

**Comment by tfinnegan937** [comment]
I can confirm that this fixes my build issues. Thank you!
