### ISSUE TITLE
gba-minrt does not build, causing samples that depend upon it to fail

### ISSUE THREAD

**Issue by tfinnegan937** [felixjones/gba-toolchain#44]
This is the output to gba-minirt's cmake process:

tim@tim-virtual-machine:/opt/gba-toolchain/lib/gba-minrt$ make
Scanning dependencies of target gba-minrt
[ 50%] Building ASM object CMakeFiles/gba-minrt.dir/src/crt0.s.o
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s: Assembler messages:
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:1: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:2: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:3: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:4: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:5: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:7: Error: unknown pseudo-op: `.syntax'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:8: Error: unknown pseudo-op: `.cpu'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:12: Error: unknown pseudo-op: `.arm'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:14: Error: no such instruction: `b entrypoint@ROM entry point'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:15: Error: can't open header.s for reading: No such file or directory
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:16: Error: no such instruction: `b entrypoint@Multiboot entry point'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:18: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:20: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:21: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:22: Error: no such instruction: `b entrypoint@JOY Bus entry point'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:25: Error: unknown pseudo-op: `.arm'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:27: Error: too many memory references for `add'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:28: Error: no such instruction: `bx r0'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:29: Error: unknown pseudo-op: `.thumb'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:30: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:31: Error: no such instruction: `ldr r3,=REG_IME'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:32: Error: no such instruction: `strh r3,[r3]'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:34: Error: no such instruction: `ldr r3,=REG_WRAMCNT'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:35: Error: no such instruction: `ldr r2,=__wramcnt'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:36: Error: too many memory references for `str'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:38: Error: no such instruction: `ldr r3,=REG_DMA3'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:40: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:41: Error: no such instruction: `ldr r0,=__iwram_lma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:42: Error: no such instruction: `ldr r1,=__iwram_vma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:43: Error: no such instruction: `ldr r2,=__iwram_dma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:44: Error: no such instruction: `bl dma_copy'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:46: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:47: Error: no such instruction: `ldr r0,=__load_start_iwram0'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:48: Error: no such instruction: `ldr r1,=__iwram_overlay_vma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:49: Error: no such instruction: `ldr r2,=__iwram_overlay_dma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:50: Error: no such instruction: `bl dma_copy'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:52: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:53: Error: too many memory references for `mov'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:54: Error: no such instruction: `ldr r1,=__iwram_bss_vma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:55: Error: no such instruction: `ldr r2,=__iwram_bss_dma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:56: Error: no such instruction: `bl dma_copy'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:58: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:59: Error: no such instruction: `ldr r0,=__ewram_lma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:60: Error: no such instruction: `ldr r1,=__ewram_vma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:61: Error: no such instruction: `ldr r2,=__ewram_dma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:62: Error: no such instruction: `bl dma_copy'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:64: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:65: Error: no such instruction: `ldr r0,=__load_start_ewram0'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:66: Error: no such instruction: `ldr r1,=__ewram_overlay_vma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:67: Error: no such instruction: `ldr r2,=__ewram_overlay_dma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:68: Error: no such instruction: `bl dma_copy'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:70: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:71: Error: too many memory references for `mov'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:72: Error: no such instruction: `ldr r1,=__ewram_bss_vma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:73: Error: no such instruction: `ldr r2,=__ewram_bss_dma'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:74: Error: no such instruction: `bl dma_copy'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:76: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:77: Error: no such instruction: `ldr r4,=__preinit_array_start'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:78: Error: no such instruction: `ldr r5,=__preinit_array_end'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:79: Error: no such instruction: `bl init_array'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:81: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:82: Error: no such instruction: `ldr r4,=__init_array_start'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:83: Error: no such instruction: `ldr r5,=__init_array_end'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:84: Error: no such instruction: `bl init_array'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:86: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:87: Warning: `r0' is not valid here (expected `(%rsi)')
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:87: Error: expecting operand after ','; got nothing
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:88: Warning: `r1' is not valid here (expected `(%rsi)')
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:88: Error: expecting operand after ','; got nothing
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:89: Warning: `r2' is not valid here (expected `(%rsi)')
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:89: Error: expecting operand after ','; got nothing
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:90: Error: no such instruction: `ldr r3,=main'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:91: Error: no such instruction: `bl bx_r3'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:92: Warning: `r7' is not valid here (expected `(%rsi)')
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:92: Warning: `r0' is not valid here (expected `(%rdi)')
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:92: Warning: no instruction mnemonic suffix given and no register operands; using default for `movs'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:94: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:95: Error: no such instruction: `ldr r4,=__fini_array_start'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:96: Error: no such instruction: `ldr r5,=__fini_array_end'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:97: Error: no such instruction: `bl fini_array'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:99: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:100: Warning: `r0' is not valid here (expected `(%rsi)')
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:100: Warning: `r7' is not valid here (expected `(%rdi)')
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:100: Warning: no instruction mnemonic suffix given and no register operands; using default for `movs'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:101: Error: no such instruction: `ldr r3,=exit'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:102: Error: no such instruction: `bl bx_r3'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:105: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:106: Error: no such instruction: `ldr r3,=REG_IME'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:107: Error: no such instruction: `strh r3,[r3]'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:108: Error: no such instruction: `b 1b'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:111: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:112: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:113: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:114: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:115: Error: junk at end of line, first unrecognized character is `@'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:116: Error: too many memory references for `lsl'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:117: Error: no such instruction: `beq dma_skip'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:118: Error: no such instruction: `stm r3!,{r0,r1,r2}'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:119: Error: too many memory references for `sub'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:121: Error: no such instruction: `bx lr'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:124: Error: too many memory references for `mov'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:125: Error: too many memory references for `cmp'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:126: Error: no such instruction: `beq init_skip'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:128: Error: no such instruction: `ldr r3,[r4]'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:129: Error: no such instruction: `bl bx_r3'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:130: Error: too many memory references for `add'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:131: Error: too many memory references for `cmp'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:132: Error: no such instruction: `bne init_loop'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:134: Error: no such instruction: `bx r6'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:137: Error: no such instruction: `bx r3'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:140: Error: too many memory references for `mov'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:141: Error: too many memory references for `cmp'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:142: Error: no such instruction: `beq fini_skip'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:144: Error: too many memory references for `sub'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:145: Error: no such instruction: `ldr r3,[r5]'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:146: Error: no such instruction: `bl bx_r3'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:147: Error: too many memory references for `cmp'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:148: Error: no such instruction: `bne fini_loop'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:150: Error: no such instruction: `bx r6'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:152: Error: unknown pseudo-op: `.pool'
/opt/gba-toolchain/lib/gba-minrt/src/crt0.s:162: Error: junk at end of line, first unrecognized character is `@'
make[2]: *** [CMakeFiles/gba-minrt.dir/build.make:75: CMakeFiles/gba-minrt.dir/src/crt0.s.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gba-minrt.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

It was produced by trying to build gba-minirt after libseven failed to build due to its dependency. That issue is tracked in  #42

**Comment by LunarLambda** [comment]
Why is it trying to compile minrt with an x86 compiler?

I skimmed the errors and it mentions x86_64 registers like rdi. You need to compile minrt with an arm-none-eabi compiler.

**Comment by tfinnegan937** [comment]
@LunarLambda After libseven failed when running the toolchain, I just CDed into the minirt folder and ran cmake to see if the toolchain was actually building it after downloading it. It's very likely that I'm missing some necessary CLI parameters to do so that the toolchain normally handles.

**Comment by felixjones** [comment]
Fixed by https://github.com/felixjones/gba-toolchain/pull/45

**Comment by tfinnegan937** [comment]
I can confirm that this has fixed this issue for me.
