### ISSUE TITLE
The toolchain still tries and fails to build GBFS in gba-toolchain/lib if -DGBFS is specified

### ISSUE THREAD

**Issue by tfinnegan937** [felixjones/gba-toolchain#46]
The -DGBFS option should override the version of GBFS pointed to by the toolchain, but currently it does not seem to do so.

The call:

cmake --toolchain /opt/gba-toolchain/arm-gba-toolchain.cmake -DGBFS=/opt/gbfs/ produces the following output while reloading the CMake file:
```
tim@tim-virtual-machine:~/CLionProjects/legacy-of-goku-new-horizons$ cmake --toolchain /opt/gba-toolchain/arm-gba-toolchain.cmake -DGBFS=/opt/gbfs/
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- Using ARM GNU toolchain (/home/tim/arm-gnu-toolchain) with GCC 11.3.1
CMake Error at /opt/gba-toolchain/cmake/Gba.cmake:63 (add_subdirectory):
  add_subdirectory given source "/opt/gba-toolchain/lib/gbfs" which is not an
  existing directory.
Call Stack (most recent call first):
  /opt/gba-toolchain/cmake/Gba.cmake:69 (_gba_add_one_library_subdirectory)
  CMakeLists.txt:4 (gba_add_library_subdirectory)


-- Configuring incomplete, errors occurred!
See also "/home/tim/CLionProjects/legacy-of-goku-new-horizons/CMakeFiles/CMakeOutput.log".
See also "/home/tim/CLionProjects/legacy-of-goku-new-horizons/CMakeFiles/CMakeError.log".

```

To bypass this, I copied my installation at /opt/gbfs/ into /opt/gba-toolchain/lib/gbfs/ and the CMake file loaded successfully.

When I went to build, however, I got the following (This is from CLion, which produces an intermediary cmake file, but the toolchain is still getting invoked):

```
====================[ Build | all | Debug ]=====================================
/snap/clion/222/bin/cmake/linux/x64/bin/cmake --build /home/tim/CLionProjects/legacy-of-goku-new-horizons/cmake-build-debug --target all -- -j 12
-- Using ARM GNU toolchain (/home/tim/arm-gnu-toolchain) with GCC 11.3.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tim/CLionProjects/legacy-of-goku-new-horizons/cmake-build-debug
Scanning dependencies of target rom
Scanning dependencies of target seven
Consolidate compiler generated dependencies of target rom
Consolidate compiler generated dependencies of target seven
Consolidate compiler generated dependencies of target gbfs
Scanning dependencies of target tonc
[  1%] Compiling GBFS assets
Consolidate compiler generated dependencies of target tonc
/bin/sh: 1: /opt/gbfs: Permission denied
gmake[2]: *** [CMakeFiles/assets.dir/build.make:71: CMakeFiles/assets] Error 126
gmake[1]: *** [CMakeFiles/Makefile2:156: CMakeFiles/assets.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[  4%] Built target rom
```

This is a simple permissions issue for the folder /opt/gbfs, but it suggests the following:

1. The -DGBFS= command does not prevent the toolchain from attempting to build the version of gbfs in gba-toolchain/lib/gbfs when reloading the CMake file.
2. GBFS isn't getting downloaded and deployed properly (Captured in #43)
3. The -DGBFS= command DOES point to that directory when building.

If a developer is using their own local version of GBFS, they do not also want to download and build the version of GBFS bundled with the toolchain.

I recommend the following behavor for -DGBFS:

1. It should cancel any attempts to download and extract GBFS
2. It should prevent the toolchain from attempting to build GBFS
3. It should direct the Makefile to the directory passed to -DGBFS when building.

Currently, -DGBFS implements Behavior 3, but not 1 or 2, which makes it unusuable without a good bit of fiddling.

**Comment by felixjones** [comment]
`-DGBFS` should point to the `gbfs` binary, not the path, and you must also point `-DBIN2S` and `-DPADBIN` to their respective binaries, otherwise the toolchain will believe one of the binaries is missing and thus download GBFS to recompile the missing binary

**Comment by tfinnegan937** [comment]
I was working on this so long ago that I can't remember if I saw this comment or resolved this issue. As a solution was posted above, however, I will mark this closed.
